package vault

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	fernet "github.com/fernet/fernet-go"
	"golang.org/x/crypto/scrypt"
)

// fixturePassphrase is the throwaway passphrase used to encrypt
// testdata/python-vault-fixture.json with the Python `cryptography` Fernet library, replicating
// server.py's _derive_key + _vault_save exactly (see the generator in the PR
// notes). It is NOT a real secret.
const fixturePassphrase = "test-passphrase-123"

// TestDecryptsPythonFixture proves the Go vault decrypts a vault.json written by
// the Python app to the exact expected plaintext (STATE-FILE COMPATIBILITY).
func TestDecryptsPythonFixture(t *testing.T) {
	src, err := os.ReadFile("testdata/python-vault-fixture.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	// Copy into a temp path so Unlock (which stats the file) works unmodified.
	dir := t.TempDir()
	path := filepath.Join(dir, "vault.json")
	if err := os.WriteFile(path, src, 0o600); err != nil {
		t.Fatal(err)
	}

	v := New(path)
	if err := v.Unlock(fixturePassphrase); err != nil {
		t.Fatalf("unlock python fixture: %v", err)
	}

	if !v.unlocked {
		t.Fatal("expected unlocked")
	}
	if v.active == nil || *v.active != "aabbccddeeff" {
		t.Fatalf("active mismatch: %v", v.active)
	}
	if len(v.tenants) != 2 {
		t.Fatalf("want 2 tenants, got %d", len(v.tenants))
	}
	want := []Tenant{
		{ID: "aabbccddeeff", Label: "Demo Tenant", Key: "Token demo-key-not-real-123"},
		{ID: "112233445566", Label: "Sandbox", Key: "Bearer eyJhbGciOiJIUzI1NiJ9.demo"},
	}
	for i, w := range want {
		if v.tenants[i] != w {
			t.Fatalf("tenant[%d] = %+v, want %+v", i, v.tenants[i], w)
		}
	}
	if v.groq != "gsk_demo_not_real" {
		t.Fatalf("groq mismatch: %q", v.groq)
	}
	if v.llmBase != "https://api.groq.com/openai/v1" || v.llmModel != "qwen/qwen3-32b" {
		t.Fatalf("llm cfg mismatch: base=%q model=%q", v.llmBase, v.llmModel)
	}

	// Wrong passphrase must be rejected.
	v2 := New(path)
	if err := v2.Unlock("definitely-wrong"); err != ErrWrongPassphrase {
		t.Fatalf("want ErrWrongPassphrase, got %v", err)
	}
}

// TestRoundTripPythonReadable proves a Go-encrypted vault re-encrypts to the
// exact on-disk envelope Python expects, and that re-deriving the key from the
// stored salt decrypts it back — the Go->Python-decryptable direction.
func TestRoundTripPythonReadable(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "vault.json")

	v := New(path)
	if err := v.Init("another-good-pass"); err != nil {
		t.Fatalf("init: %v", err)
	}
	active := "t1"
	v.tenants = []Tenant{{ID: "t1", Label: "Roundtrip", Key: "Token rt-key"}}
	v.active = &active
	v.groq = "gsk_rt"
	if err := v.Save(); err != nil {
		t.Fatalf("save: %v", err)
	}

	// Envelope shape must be exactly {v, salt, data} that Python's json.load reads.
	raw, _ := os.ReadFile(path)
	var env fileEnvelope
	if err := json.Unmarshal(raw, &env); err != nil {
		t.Fatalf("envelope not parseable: %v", err)
	}
	// A vault this build creates is written at the CURRENT version, not the
	// legacy 1 this used to pin. The literal that was here is exactly the kind of
	// hardcoded version save() no longer emits.
	if env.V != currentVaultVersion || env.Salt == "" || env.Data == "" {
		t.Fatalf("bad envelope: %+v (want v=%d)", env, currentVaultVersion)
	}

	// Independent reader (fresh Vault) re-derives the key from salt and decrypts,
	// exactly as Python's vault_unlock would.
	v3 := New(path)
	if err := v3.Unlock("another-good-pass"); err != nil {
		t.Fatalf("reopen: %v", err)
	}
	if v3.active == nil || *v3.active != "t1" || len(v3.tenants) != 1 ||
		v3.tenants[0].Key != "Token rt-key" || v3.groq != "gsk_rt" {
		t.Fatalf("roundtrip data mismatch: %+v", v3)
	}
}

// --- versioned KDF migration --------------------------------------------------
//
// WHAT IS AT STAKE. The vault holds live Infoblox API keys and there is no
// recovery path: no escrow, no second copy, no reset that keeps the contents. A
// migration that wrote the new version number beside a token still sealed with
// the OLD key would produce a file that no build, no passphrase and no operator
// can ever open again. So these tests are not about the new parameters being
// stronger — they are about every failure mode leaving the operator with a vault
// they can still open.
//
// The ground truth for backward compatibility is testdata/python-vault-fixture.json,
// a REAL v1 vault written by the retired Python server. It is copied, never
// modified: if it were regenerated by this code it would stop being evidence.

// v1FixtureCopy writes the Python v1 fixture into a fresh temp dir and returns
// the copy's path. HOME is sandboxed for the same reason writelock_test.go does
// it — nothing here may be able to reach a developer's real vault directory.
func v1FixtureCopy(t *testing.T) string {
	t.Helper()
	t.Setenv("HOME", t.TempDir())
	src, err := os.ReadFile("testdata/python-vault-fixture.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	path := filepath.Join(t.TempDir(), "vault.json")
	if err := os.WriteFile(path, src, 0o600); err != nil {
		t.Fatal(err)
	}
	// The fixture must actually be the legacy version, or every migration
	// assertion below is testing a migration that never had to happen.
	if got := readEnvelope(t, path).V; got != 1 {
		t.Fatalf("the v1 fixture is not v1 (v=%d) — these tests would prove nothing", got)
	}
	return path
}

// readEnvelope parses the cleartext wrapper straight off disk.
func readEnvelope(t *testing.T, path string) fileEnvelope {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var env fileEnvelope
	if err := json.Unmarshal(b, &env); err != nil {
		t.Fatalf("parse envelope at %s: %v", path, err)
	}
	return env
}

// captureLog redirects the standard logger for one test. A migration that fails
// must SAY SO — a silent failure would leave the vault quietly on the old
// parameters forever with nobody able to notice.
func captureLog(t *testing.T) *bytes.Buffer {
	t.Helper()
	var buf bytes.Buffer
	prevOut, prevFlags := log.Writer(), log.Flags()
	log.SetOutput(&buf)
	log.SetFlags(0)
	t.Cleanup(func() { log.SetOutput(prevOut); log.SetFlags(prevFlags) })
	return &buf
}

// fixtureTenants is the exact plaintext inside the Python fixture. Migration is
// only correct if this survives it byte for byte.
var fixtureTenants = []Tenant{
	{ID: "aabbccddeeff", Label: "Demo Tenant", Key: "Token demo-key-not-real-123"},
	{ID: "112233445566", Label: "Sandbox", Key: "Bearer eyJhbGciOiJIUzI1NiJ9.demo"},
}

// assertFixturePayload checks a vault holds exactly what the fixture contains.
func assertFixturePayload(t *testing.T, v *Vault, when string) {
	t.Helper()
	if len(v.tenants) != len(fixtureTenants) {
		t.Fatalf("%s: %d tenants, want %d", when, len(v.tenants), len(fixtureTenants))
	}
	for i, w := range fixtureTenants {
		if v.tenants[i] != w {
			t.Fatalf("%s: tenant[%d] = %+v, want %+v", when, i, v.tenants[i], w)
		}
	}
	if v.active == nil || *v.active != "aabbccddeeff" {
		t.Fatalf("%s: active = %v", when, v.active)
	}
	if v.groq != "gsk_demo_not_real" || v.llmBase != "https://api.groq.com/openai/v1" ||
		v.llmModel != "qwen/qwen3-32b" {
		t.Fatalf("%s: llm cfg = %q %q %q", when, v.groq, v.llmBase, v.llmModel)
	}
}

// TestMigrate_V1FixtureUpgradesInPlaceAndKeepsEveryCredential is the headline
// property: opening a real Python-era vault upgrades the FILE, changes nothing
// an operator can observe, and leaves the SAME PASSPHRASE opening it afterwards.
//
// The reopen is done with a brand-new Vault so nothing in memory can answer for
// the file — this is the assertion that a migration writing a mismatched
// key/version pair would redden, and it is the only one that would.
func TestMigrate_V1FixtureUpgradesInPlaceAndKeepsEveryCredential(t *testing.T) {
	path := v1FixtureCopy(t)
	saltBefore := readEnvelope(t, path).Salt

	v := New(path)
	if err := v.Unlock(fixturePassphrase); err != nil {
		t.Fatalf("unlock the v1 fixture: %v", err)
	}
	assertFixturePayload(t, v, "in memory right after unlocking v1")
	if v.ver != currentVaultVersion {
		t.Errorf("after a successful migration v.ver = %d, want %d — the in-memory version did not "+
			"follow the key, so the NEXT save would write the wrong envelope", v.ver, currentVaultVersion)
	}

	env := readEnvelope(t, path)
	if env.V != currentVaultVersion {
		t.Fatalf("on-disk version is still %d after unlocking a v1 vault — the migration did not run", env.V)
	}
	// The salt is deliberately carried over: it is already 16 crypto/rand bytes
	// and re-minting it would make one operation change two things. Rotate is
	// what refreshes a salt.
	if env.Salt != saltBefore {
		t.Errorf("migration changed the salt (%q -> %q); it is supposed to reuse it", saltBefore, env.Salt)
	}

	// The passphrase the operator still has must still open it, from cold.
	reopened := New(path)
	if err := reopened.Unlock(fixturePassphrase); err != nil {
		t.Fatalf("THE MIGRATED VAULT NO LONGER OPENS WITH THE OPERATOR'S PASSPHRASE (%v) — "+
			"this is the permanent-lockout failure the whole migration is built to avoid", err)
	}
	assertFixturePayload(t, reopened, "after reopening the migrated file")
	if reopened.ver != currentVaultVersion {
		t.Errorf("reopened v.ver = %d, want %d", reopened.ver, currentVaultVersion)
	}

	// And a wrong passphrase is still wrong — the migration must not have made
	// the file openable by anything else.
	if err := New(path).Unlock("definitely-wrong"); err != ErrWrongPassphrase {
		t.Errorf("after migration a wrong passphrase gives %v, want ErrWrongPassphrase", err)
	}
}

// TestMigrate_MigratedFileIsNoLongerReadableWithLegacyParameters is the TRAP
// TEST. Every other assertion here would still pass if the migration had
// rewritten the version number and left the token sealed under the v1 key,
// because the reader picks its parameters from that same version number — the
// two lies cancel out on the way back in.
//
// So this decrypts the file by hand with the LEGACY cost, using scrypt directly
// with literal parameters rather than kdfByVersion, so that editing the map
// cannot make this test agree with the code it is checking.
//
// It asserts BOTH directions. The v1 derive must fail AND the v2 derive must
// succeed: without the positive control, a typo in the salt or the passphrase
// here would make the negative assertion pass while proving nothing at all.
func TestMigrate_MigratedFileIsNoLongerReadableWithLegacyParameters(t *testing.T) {
	path := v1FixtureCopy(t)

	// Before: the legacy derive is the ONE that works. This is the control that
	// makes the "after" half meaningful.
	env := readEnvelope(t, path)
	salt, err := base64.StdEncoding.DecodeString(env.Salt)
	if err != nil {
		t.Fatalf("decode fixture salt: %v", err)
	}
	if handDecrypt(t, env.Data, salt, 1<<15) == nil {
		t.Fatal("the hand-rolled v1 derive cannot open the UNMIGRATED v1 fixture — the oracle in this " +
			"test is broken, so its verdict after the migration would be worthless")
	}

	if err := New(path).Unlock(fixturePassphrase); err != nil {
		t.Fatalf("unlock: %v", err)
	}

	after := readEnvelope(t, path)
	saltAfter, err := base64.StdEncoding.DecodeString(after.Salt)
	if err != nil {
		t.Fatalf("decode migrated salt: %v", err)
	}
	if plain := handDecrypt(t, after.Data, saltAfter, 1<<15); plain != nil {
		t.Error("THE MIGRATED FILE STILL DECRYPTS UNDER scrypt N=2^15: only the version number moved. " +
			"The bytes on disk are still protected at the old cost while the envelope claims otherwise")
	}
	plain := handDecrypt(t, after.Data, saltAfter, 1<<17)
	if plain == nil {
		t.Fatal("the migrated file does not decrypt under scrypt N=2^17 either — it is sealed with " +
			"neither generation's parameters and may not be openable at all")
	}
	// And it is still the operator's data, not an empty vault written over it.
	if !strings.Contains(string(plain), "Token demo-key-not-real-123") {
		t.Errorf("the migrated ciphertext does not contain the fixture's tenant key: %s", plain)
	}
}

// handDecrypt derives a Fernet key from literal scrypt parameters — no shared
// helper, no kdfByVersion — and tries the token. nil means it did not open.
func handDecrypt(t *testing.T, token string, salt []byte, n int) []byte {
	t.Helper()
	dk, err := scrypt.Key([]byte(fixturePassphrase), salt, n, 8, 1, 32)
	if err != nil {
		t.Fatalf("scrypt(N=%d): %v", n, err)
	}
	k, err := fernet.DecodeKey(base64.URLEncoding.EncodeToString(dk))
	if err != nil {
		t.Fatalf("decode fernet key: %v", err)
	}
	return fernet.VerifyAndDecrypt([]byte(token), 0, []*fernet.Key{k})
}

// TestMigrate_NativeCurrentVersionRoundTripsAndDoesNotRewrite covers the vault
// this build creates for itself: it is born current, so unlocking it must NOT
// trigger a migration. A migration that fired on every unlock would rewrite the
// credential file on every startup for no reason — a needless write against the
// one file with no backup.
func TestMigrate_NativeCurrentVersionRoundTripsAndDoesNotRewrite(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	path := filepath.Join(t.TempDir(), "vault.json")

	v := New(path)
	if err := v.Init("native-current-version-pass"); err != nil {
		t.Fatalf("init: %v", err)
	}
	id := "t-native"
	v.tenants = []Tenant{{ID: id, Label: "Native", Key: "Token native-key"}}
	v.active = &id
	if err := v.Save(); err != nil {
		t.Fatalf("save: %v", err)
	}
	if v.ver != currentVaultVersion {
		t.Errorf("Init left v.ver = %d, want %d", v.ver, currentVaultVersion)
	}
	before := readEnvelope(t, path)
	if before.V != currentVaultVersion {
		t.Fatalf("Init wrote v=%d, want %d", before.V, currentVaultVersion)
	}

	reopened := New(path)
	if err := reopened.Unlock("native-current-version-pass"); err != nil {
		t.Fatalf("reopen a natively-current vault: %v", err)
	}
	if reopened.ActiveKey() != "Token native-key" {
		t.Errorf("round trip lost the tenant key: %q", reopened.ActiveKey())
	}
	if after := readEnvelope(t, path); after != before {
		t.Errorf("unlocking an already-current vault rewrote it:\n before %+v\n after  %+v", before, after)
	}
}

// TestUnlock_RefusesAVersionItCannotDerive: a file from a NEWER build must be
// refused by name, and must not come back as ErrWrongPassphrase. The difference
// is not cosmetic — "wrong passphrase" sends an operator to rotate or re-store a
// secret that was never the problem, and `vault-passphrase check` reports the
// two outcomes with different exit codes.
//
// The vault must also stay LOCKED: a refused unlock that had populated half the
// struct would leave a locked vault holding live state.
//
// NOT ASSERTED, DELIBERATELY: that the refusal happens BEFORE the scrypt call
// rather than inside deriveKey (which carries the same guard, so either order is
// CORRECT — the early one just declines to spend ~128 MiB and a few hundred
// milliseconds on a file it has already decided it cannot open). The only
// observable difference is time and memory, and a wall-clock assertion here
// would be exactly the kind of pinned measurement that has already had to be
// deleted from this repo once. Do not add one.
func TestUnlock_RefusesAVersionItCannotDerive(t *testing.T) {
	path := v1FixtureCopy(t)
	env := readEnvelope(t, path)
	env.V = 99
	b, err := json.Marshal(env)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, b, 0o600); err != nil {
		t.Fatal(err)
	}

	v := New(path)
	err = v.Unlock(fixturePassphrase)
	if err == nil {
		t.Fatal("a v99 vault unlocked; this build derived a key with parameters it does not have")
	}
	if err == ErrWrongPassphrase {
		t.Fatal("a v99 vault reports ErrWrongPassphrase — the operator would be told to fix a " +
			"passphrase that is perfectly correct, instead of to upgrade the binary")
	}
	if !strings.Contains(err.Error(), "99") {
		t.Errorf("the refusal does not name the version it could not handle: %q", err)
	}
	if v.IsUnlocked() || v.TenantCount() != 0 || v.ActiveKey() != "" {
		t.Errorf("a refused unlock left state behind: unlocked=%v count=%d", v.IsUnlocked(), v.TenantCount())
	}
	if err := v.Save(); err == nil {
		t.Error("a vault refused for an unknown version can still save — it is holding a derived key")
	}
	// The file itself must be untouched: this build does not get to rewrite a
	// vault it does not understand.
	if got := readEnvelope(t, path).V; got != 99 {
		t.Errorf("the refused file was rewritten (v=%d)", got)
	}
}

// TestMigrate_SaveFailureLeavesTheVaultOpenAndTheFileIntact is the failure mode
// that actually decides whether this feature is safe to ship. A read-only state
// directory, a full disk or a container mount that lost its write bit must NOT
// turn "your vault opened" into "your vault will not open".
//
// Three things are asserted: the unlock SUCCEEDS anyway, the file is still the
// original v1 (tmp+rename means a failed write cannot leave a partial one), and
// the failure is LOGGED rather than swallowed.
func TestMigrate_SaveFailureLeavesTheVaultOpenAndTheFileIntact(t *testing.T) {
	if runtime.GOOS == "windows" || os.Geteuid() == 0 {
		t.Skip("this fixture needs a non-root POSIX run: mode bits do not deny writes to root")
	}
	path := v1FixtureCopy(t)
	before, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	dir := filepath.Dir(path)
	if err := os.Chmod(dir, 0o500); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(dir, 0o755) }) // so TempDir cleanup can remove it

	logs := captureLog(t)
	v := New(path)
	if err := v.Unlock(fixturePassphrase); err != nil {
		t.Fatalf("a vault that could not be UPGRADED refused to OPEN (%v) — a failed optimisation "+
			"took the operator's credentials away from them", err)
	}
	assertFixturePayload(t, v, "after an unlock whose migration could not be written")

	// The file is untouched, so it is still the v1 file the operator had.
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(before, after) {
		t.Fatalf("a FAILED migration still changed vault.json:\n before %s\n after  %s", before, after)
	}
	if got := readEnvelope(t, path).V; got != 1 {
		t.Errorf("on-disk version = %d after a failed migration, want 1", got)
	}
	// In-memory version must have rolled back with the key. If it had not, the
	// next ordinary save() (adding a tenant, say) would stamp v2 on a token
	// sealed with the v1 key and the vault would never open again.
	if v.ver != 1 {
		t.Errorf("v.ver = %d after a FAILED migration, want 1 — the version did not roll back with "+
			"the key, so the next save writes an unopenable file", v.ver)
	}
	if !strings.Contains(logs.String(), "key-derivation") {
		t.Errorf("the failed migration was not reported to the operator; log was: %q", logs.String())
	}

	// And the whole point: it still opens, cold, with the same passphrase.
	if err := os.Chmod(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	reopened := New(path)
	if err := reopened.Unlock(fixturePassphrase); err != nil {
		t.Fatalf("the vault left behind by a failed migration no longer opens: %v", err)
	}
	assertFixturePayload(t, reopened, "reopening after a failed migration")
	// Now that the directory is writable the retry lands, which is what "it will
	// be retried at the next unlock" in the log message has to mean.
	if got := readEnvelope(t, path).V; got != currentVaultVersion {
		t.Errorf("the migration did not retry on the next unlock: on-disk v=%d", got)
	}
}

// TestRotate_UpgradesALegacyVaultToTheCurrentVersion: a rotate re-derives and
// rewrites everything anyway, so a vault still on v1 when it happens must come
// out current. If Rotate kept v.ver, a legacy vault whose migration had failed
// would stay legacy forever, even through the one command that re-keys it.
//
// The v1-in-memory state is set up by BLOCKING the migration with a DIRECTORY at
// the exact path save() writes its temp file to. That fails with EISDIR for
// every user including root — unlike a chmod, which root ignores — so this test
// is never silently vacuous on a CI runner.
func TestRotate_UpgradesALegacyVaultToTheCurrentVersion(t *testing.T) {
	path := v1FixtureCopy(t)
	blocker := path + ".tmp"
	if err := os.Mkdir(blocker, 0o755); err != nil {
		t.Fatal(err)
	}

	captureLog(t)
	v := New(path)
	if err := v.Unlock(fixturePassphrase); err != nil {
		t.Fatalf("unlock: %v", err)
	}
	if v.ver != 1 || readEnvelope(t, path).V != 1 {
		t.Fatalf("the migration-blocking fixture did not block anything (v.ver=%d, on-disk v=%d) — "+
			"this test would not be rotating a legacy vault at all", v.ver, readEnvelope(t, path).V)
	}

	if err := os.Remove(blocker); err != nil {
		t.Fatal(err)
	}
	const newPass = "rotated-off-the-legacy-kdf"
	if err := v.Rotate(newPass); err != nil {
		t.Fatalf("rotate: %v", err)
	}

	if v.ver != currentVaultVersion {
		t.Errorf("after Rotate v.ver = %d, want %d", v.ver, currentVaultVersion)
	}
	env := readEnvelope(t, path)
	if env.V != currentVaultVersion {
		t.Fatalf("Rotate on a v1 vault wrote v=%d, want %d", env.V, currentVaultVersion)
	}
	// Rotate mints a fresh salt, unlike the migration. (The fixture's salt is the
	// literal 00..0f the Python generator used, so this comparison is exact.)
	if env.Salt == "AAECAwQFBgcICQoLDA0ODw==" {
		t.Error("Rotate reused the fixture's salt; it is supposed to mint a new one")
	}

	reopened := New(path)
	if err := reopened.Unlock(newPass); err != nil {
		t.Fatalf("the rotated legacy vault does not open with the new passphrase: %v", err)
	}
	assertFixturePayload(t, reopened, "after rotating a legacy vault")
	if err := New(path).Unlock(fixturePassphrase); err != ErrWrongPassphrase {
		t.Errorf("the OLD passphrase still opens the rotated vault (%v)", err)
	}
}

// TestKDFTable_V1ParametersAreFrozen guards the one edit in this package that
// would lock every existing operator out at once and could not be undone by
// them: changing what v1 means. Those numbers describe files that were sealed
// years ago and are sitting on disks right now; nothing this repo does can
// re-encrypt them, so the row is evidence, not configuration.
//
// If you are here because this test failed: you cannot fix a weak KDF by editing
// this row. Add a NEW version to kdfByVersion, bump currentVaultVersion, and let
// Unlock migrate — which is exactly what version 2 is.
func TestKDFTable_V1ParametersAreFrozen(t *testing.T) {
	got, ok := kdfByVersion[1]
	if !ok {
		t.Fatal("kdfByVersion has no entry for version 1 — every vault written before this change, " +
			"including every one still in the field, is now permanently unopenable")
	}
	want := kdfParams{N: 1 << 15, R: 8, P: 1, KeyLen: 32}
	if got != want {
		t.Fatalf("the v1 scrypt parameters changed: %+v, want %+v. This does not re-encrypt anyone's "+
			"vault; it makes every v1 vault report a wrong passphrase forever", got, want)
	}
	if _, ok := kdfByVersion[currentVaultVersion]; !ok {
		t.Fatalf("currentVaultVersion is %d but kdfByVersion has no parameters for it — every save "+
			"would write a file this build refuses to read", currentVaultVersion)
	}
}

// TestSave_RefusesAVersionItCannotDerive pins the last-ditch guard in save().
// It is unreachable through the public API today (every assignment of v.key
// assigns v.ver in the same statement), which is precisely why it is worth a
// test: nothing else would notice if a future edit made it reachable, and the
// file it would otherwise write is one nobody can ever open.
func TestSave_RefusesAVersionItCannotDerive(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	path := filepath.Join(t.TempDir(), "vault.json")
	v := New(path)
	if err := v.Init("save-guard-test-pass"); err != nil {
		t.Fatalf("init: %v", err)
	}
	good, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}

	v.ver = 99 // as a bad merge or a half-finished v3 would leave it
	err = v.Save()
	if err == nil {
		t.Fatal("save() wrote an envelope claiming a version this build cannot derive; the file it " +
			"just produced can never be unlocked")
	}
	if !strings.Contains(err.Error(), "99") {
		t.Errorf("the refusal does not name the version: %q", err)
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(good, after) {
		t.Error("the refused save still touched vault.json")
	}
}
