#!/usr/bin/env bash
# Runs the SHIPPED `bloxsmith audit verify` binary and asserts every one of its
# three verdicts, its exit codes, and its two refusals.
#
# WHY A SHELL SCRIPT AND NOT ONLY GO TESTS. The Go tests in
# go/internal/audit/readonly_test.go cover the package. They do not cover the
# thing an operator actually types: flag parsing, defaults, exit codes, the words
# printed. Three defects this week came from exactly that gap — a broken
# install.sh that `bash -n` passed, a privacy scan that was dead on macOS, and a
# Windows installer that had never once been parsed. So this executes the real
# artifact and reads its real output.
#
# Kept as a committed script rather than inline YAML for the reason recorded in
# v3.24.0: inline refusal logic in a workflow file broke on its own quoting twice,
# and a committed script can be run locally, unchanged, before it is pushed.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

BIN="$WORK/bloxsmith"
fails=0

say()  { printf '\n=== %s\n' "$1"; }
pass() { printf '  ok   %s\n' "$1"; }
fail() { printf '  FAIL %s\n' "$1"; fails=$((fails + 1)); }

# assert_run <expected-exit> <expected-substring> <label> -- <args...>
assert_run() {
  local want_code="$1" want_text="$2" label="$3"; shift 4
  local out code
  out="$("$BIN" audit verify "$@" 2>&1)"
  code=$?
  if [ "$code" != "$want_code" ]; then
    fail "$label: exit $code, want $want_code"
    printf '       output: %s\n' "$out"
    return
  fi
  case "$out" in
    *"$want_text"*) pass "$label (exit $code)";;
    *) fail "$label: exit code was right but the output never said '$want_text'"
       printf '       output: %s\n' "$out";;
  esac
}

say "build the binary under test"
( cd "$ROOT/go" && go build -o "$BIN" . ) || { fail "go build"; exit 1; }
[ -x "$BIN" ] || { fail "no binary produced"; exit 1; }
pass "built"

# --- fixture: a real signed chain, written by the real code ------------------
# Generated by running the server's own audit writer, not hand-authored: a
# hand-written fixture would only prove the verifier agrees with my idea of the
# format.
say "fixture: a genuine 5-entry signed chain"
STATE="$WORK/state"; TRUST="$WORK/trust"
mkdir -p "$STATE" "$TRUST"
( cd "$ROOT/go" && go run ./cmd/auditfixture "$STATE" "$TRUST" ) || fail "could not generate the fixture chain"
LOG="$STATE/audit_log.jsonl"
[ -s "$LOG" ] && pass "chain written ($(wc -l < "$LOG" | tr -d ' ') lines)" || fail "no chain written"

say "1. a genuine chain verifies -> intact, exit 0"
assert_run 0 "intact" "genuine chain" -- --log "$LOG" --trust-dir "$TRUST"

say "2. --json emits a machine-readable verdict"
JOUT="$("$BIN" audit verify --log "$LOG" --trust-dir "$TRUST" --json 2>&1)"
case "$JOUT" in
  *'"verdict": "intact"'*) pass "json verdict field";;
  *) fail "json output has no intact verdict: $JOUT";;
esac
case "$JOUT" in
  *'"exit_code": 0'*) pass "json carries the exit code";;
  *) fail "json output has no exit_code";;
esac

say "3. entries cut off the end -> tampered, exit 1"
cp "$LOG" "$WORK/full.jsonl"
head -n 3 "$WORK/full.jsonl" > "$LOG"
assert_run 1 "removed from the end" "truncated tail" -- --log "$LOG" --trust-dir "$TRUST"
cp "$WORK/full.jsonl" "$LOG"

say "4. an edited entry -> tampered, exit 1"
# Note the space after the colon: that is the canonical on-disk form. A pattern
# without it silently matches nothing, and the check then passes on an untouched
# file — which is exactly how the Go version of this test first went green.
sed 's/"n": 2/"n": 999/' "$WORK/full.jsonl" > "$LOG"
if cmp -s "$LOG" "$WORK/full.jsonl"; then
  fail "the edit did not change the file, so this case would assert nothing"
else
  assert_run 1 "tampered" "edited entry" -- --log "$LOG" --trust-dir "$TRUST"
fi
cp "$WORK/full.jsonl" "$LOG"

say "5. a different key -> could-not-verify (exit 2), NOT tampered"
# A rotated or lost trust root is not an accusation. Reporting it as tampering
# would be a fabricated claim against a log that may be perfectly intact.
OTHER="$WORK/other-trust"; mkdir -p "$OTHER"
printf '%s\n' "$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')" > "$OTHER/audit.key"
chmod 600 "$OTHER/audit.key"
assert_run 2 "could-not-verify" "foreign key" -- --log "$LOG" --trust-dir "$OTHER"
OUT5="$("$BIN" audit verify --log "$LOG" --trust-dir "$OTHER" 2>&1)"
case "$OUT5" in
  *tampered*) fail "a foreign key was reported as TAMPERING — that is a false accusation";;
  *) pass "a foreign key is not called tampering";;
esac

say "6. no key at all -> could-not-verify, and NO key is created"
EMPTY="$WORK/empty-trust"; mkdir -p "$EMPTY"
assert_run 2 "could-not-verify" "no key available" -- --log "$LOG" --trust-dir "$EMPTY"
if [ -e "$EMPTY/audit.key" ]; then
  fail "verifying CREATED a key — it would then be attesting a trust root it just invented"
else
  pass "no key was created by verifying"
fi
if [ -n "$(ls -A "$EMPTY" 2>/dev/null)" ]; then
  fail "verifying wrote files into the trust directory: $(ls -A "$EMPTY")"
else
  pass "trust directory untouched"
fi

say "7. verifying never modifies the log or the seal"
BEFORE_LOG="$(shasum "$LOG" | cut -d' ' -f1)"
BEFORE_TRUST="$(find "$TRUST" -type f -exec shasum {} \; | shasum | cut -d' ' -f1)"
"$BIN" audit verify --log "$LOG" --trust-dir "$TRUST" >/dev/null 2>&1
AFTER_LOG="$(shasum "$LOG" | cut -d' ' -f1)"
AFTER_TRUST="$(find "$TRUST" -type f -exec shasum {} \; | shasum | cut -d' ' -f1)"
[ "$BEFORE_LOG" = "$AFTER_LOG" ] && pass "log unchanged" || fail "the log changed during verification"
[ "$BEFORE_TRUST" = "$AFTER_TRUST" ] && pass "seal unchanged" || fail "the sealed head changed during verification"

say "8. a log that is not there -> could-not-verify, not intact"
assert_run 2 "could not be opened" "missing log" -- --log "$WORK/nope.jsonl" --trust-dir "$TRUST"

say "9. bad usage is its own exit code (3), distinct from a verdict"
"$BIN" audit verify --nonsense >/dev/null 2>&1
[ $? = 3 ] && pass "unknown option -> exit 3" || fail "unknown option did not exit 3"
"$BIN" audit verify --log >/dev/null 2>&1
[ $? = 3 ] && pass "missing flag value -> exit 3" || fail "missing flag value did not exit 3"

printf '\n'
if [ "$fails" = 0 ]; then
  printf 'audit-verify-test: ALL CHECKS PASSED\n'
  exit 0
fi
printf 'audit-verify-test: %d CHECK(S) FAILED\n' "$fails"
exit 1
