#!/usr/bin/env node
/* build_ui.js — Bloxsmith UI build (Phase 1: split source, compile once, no bundler).
 *
 * Concatenates every src/*.jsx (in FILENAME order — numeric prefixes define the
 * order) into ONE module, lowers JSX to react/jsx-runtime calls using the ALREADY-
 * VENDORED babel.min.js (@babel/standalone) under Node, and writes app.bundle.js next
 * to index.html. index.html loads it as a native ES module (react / jsx-runtime /
 * react-dom / @astryxdesign/core resolved by vendor.importmap.json).
 *
 * Why concat, not per-file ESM: the ~180 top-level symbols share one scope today.
 * Concatenating verbatim source slices keeps that single scope, so the compiled output
 * is behaviorally identical to the old inline script — the split buys parallel-editable
 * files + kills in-browser Babel, at ~zero behavior risk. Individual fragments can later
 * graduate to real import/export modules where a boundary actually pays (e.g. the P2
 * write module).
 *
 * NO @babel/core, NO node_modules in the container, NO network. The container still
 * just serves the static app.bundle.js — babel.min.js is deleted from index.html.
 *
 * Usage:  node scripts/build_ui.js           # build app.bundle.js
 *         node scripts/build_ui.js --check    # fail if app.bundle.js is stale (CI gate)
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const OUT = path.join(ROOT, 'app.bundle.js');
const Babel = require(path.join(ROOT, 'babel.min.js'));
const CHECK = process.argv.includes('--check');

function build() {
  if (!fs.existsSync(SRC)) { console.error('build_ui: no src/ — nothing to build.'); process.exit(0); }
  const files = fs.readdirSync(SRC).filter(f => f.endsWith('.jsx')).sort();
  if (!files.length) { console.error('build_ui: src/ has no .jsx files.'); process.exit(0); }

  // Concatenate verbatim; a banner comment per fragment keeps stack traces / greps
  // pointing back at the source file without shifting any code semantics.
  const source = files.map(f =>
    `\n/* ==== src/${f} ==== */\n` + fs.readFileSync(path.join(SRC, f), 'utf8')
  ).join('');

  let code = Babel.transform(source, {
    filename: 'app.bundle.jsx',
    presets: [['react', { runtime: 'automatic' }]],
  }).code;

  // Minify with esbuild (Vite's engine) — ~35% smaller, faster parse. esbuild only
  // runs at build time (dev/CI), never in the container. Degrades GRACEFULLY: if
  // esbuild isn't available (offline, no npx), ship the readable bundle so the app
  // never breaks — just larger. The importmap resolves the bare specifiers either way.
  let minified = false;
  try {
    const cp = require('child_process');
    const tmp = path.join(require('os').tmpdir(), 'bx-bundle-' + process.pid + '.js');
    fs.writeFileSync(tmp, code);
    // --keep-names: preserve function/class .name (TAB_COMPONENTS etc. map by identifier,
    // but any name-based logic stays intact); ESM so import statements survive.
    // Pinned version → deterministic output so `--check` is stable across CI runs.
    const min = cp.execSync(`npx -y esbuild@0.28.1 "${tmp}" --minify --keep-names --format=esm --legal-comments=none`,
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], maxBuffer: 32 * 1024 * 1024 });
    fs.unlinkSync(tmp);
    if (min && min.length > 100) { code = min; minified = true; }
  } catch (e) {
    console.error('build_ui: esbuild minify unavailable — shipping readable bundle.');
  }

  const banner = '/* AUTO-GENERATED by scripts/build_ui.js from src/*.jsx — do not edit; edit the source.'
    + (minified ? ' minified by esbuild.' : '') + ' */\n';
  const out = banner + code + (code.endsWith('\n') ? '' : '\n');

  const prev = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
  if (CHECK) {
    if (prev !== out) { console.error('STALE: app.bundle.js out of date — run: node scripts/build_ui.js'); process.exit(1); }
    console.log(`build_ui --check: app.bundle.js current (${files.length} fragments).`);
  } else {
    fs.writeFileSync(OUT, out);
    console.log(`build_ui: app.bundle.js written from ${files.length} fragments (${(out.length/1024).toFixed(0)} KB).`);
  }
}

build();
