#!/usr/bin/env bash
# dev-serve.sh — persistent bleeding-edge dev server on :8090.
#
# v3 stack: UI lives in ui/ (Vite), server lives in go/ (compiled binary, not
# `go run` — no orphan processes). Runs with DISABLE_UPDATE_CHECK=1 (never
# self-updates away) and WEB_DIR=go/web (serves the UI from disk).
#
# Watches TWO independent signatures:
#   - UI  (ui/src, ui/index.html, ui/vite.config.js) -> rebuild_web only,
#     copies dist into go/web, NO binary restart.
#   - Go  (go/**/*.go excluding go/web, go/go.mod, go/go.sum) -> rebuild the
#     binary to a temp path, health-check it, then restart onto it.
# go/web is excluded from sig_go on purpose: it is generated BY rebuild_web,
# so hashing it would make every UI build trigger a Go rebuild + restart,
# forever.
#
# A failed UI build never advances its signature, so the next loop iteration
# retries against the same failing state. A Go build failure or a Go binary
# that builds but fails its post-restart health check rolls back to the
# previous binary and does NOT advance LAST_GO — but LAST_TRIED_GO is
# advanced regardless, so that failing state is retried only when the Go
# sources change again, not on every 2s tick.
#
# Standalone runnable: scripts/dev-serve.sh [port]
# NOTE: this script is no longer supervised by a launchd watch job — it is
# meant to be run directly in a terminal/tmux session and stopped with
# Ctrl-C (SIGINT) or `kill -TERM <pid>`.
set -uo pipefail

PORT="${1:-8090}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1
BIN="/tmp/bloxsmith-dev"
# BIN is built to /tmp, and config.go defaults TemplatesDir relative to the
# binary's own directory (not the repo) — without TEMPLATES_DIR set here the
# dev server silently finds no templates, breaking Provision/Drift dropdowns.
export WEB_DIR="$ROOT/go/web" DISABLE_UPDATE_CHECK=1 PORT TEMPLATES_DIR="$ROOT/go/templates"

command -v node   >/dev/null 2>&1 || { echo "dev-serve: node not found"   >&2; exit 1; }
command -v go     >/dev/null 2>&1 || { echo "dev-serve: go not found"     >&2; exit 1; }
command -v shasum >/dev/null 2>&1 || { echo "dev-serve: shasum not found" >&2; exit 1; }
command -v curl   >/dev/null 2>&1 || { echo "dev-serve: curl not found"   >&2; exit 1; }

rebuild_web(){ ( cd ui && npm run build >/dev/null 2>&1 ) && rm -rf go/web/* && cp -R ui/dist/* go/web/; }

# Deterministic, order-independent, rename-sensitive signatures: sorted
# NUL-delimited filename list, each file hashed, then hash-of-hashes.
sig_ui(){
  find ui/src ui/index.html ui/vite.config.js -type f -print0 2>/dev/null \
    | sort -z | xargs -0 shasum 2>/dev/null | shasum | cut -d' ' -f1
}
sig_go(){
  { find go -type f -name '*.go' -not -path 'go/web/*' -print0 2>/dev/null; \
    printf '%s\0' go/go.mod go/go.sum; } \
    | sort -z | xargs -0 shasum 2>/dev/null | shasum | cut -d' ' -f1
}

health_check(){
  local tries=0
  while [ "$tries" -lt 10 ]; do
    curl -fsS -o /dev/null "http://localhost:$PORT/" 2>/dev/null && return 0
    sleep 0.5
    tries=$((tries + 1))
  done
  return 1
}

STOPPING=0

restart_binary(){
  if [ -n "${SRV:-}" ] && kill -0 "$SRV" 2>/dev/null; then
    kill -TERM "$SRV" 2>/dev/null
    local waited=0
    while kill -0 "$SRV" 2>/dev/null && [ "$waited" -lt 25 ]; do
      sleep 0.2
      waited=$((waited + 1))
    done
    kill -0 "$SRV" 2>/dev/null && kill -9 "$SRV" 2>/dev/null
  fi
  "$BIN" & SRV=$!
}

start(){ "$BIN" & SRV=$!; }

cleanup(){
  if [ -n "${SRV:-}" ] && kill -0 "$SRV" 2>/dev/null; then
    kill -TERM "$SRV" 2>/dev/null
    local waited=0
    while kill -0 "$SRV" 2>/dev/null && [ "$waited" -lt 25 ]; do
      sleep 0.2
      waited=$((waited + 1))
    done
    kill -0 "$SRV" 2>/dev/null && kill -9 "$SRV" 2>/dev/null
  fi
}

on_term(){
  STOPPING=1
  cleanup
  exit 0
}
trap on_term INT TERM
trap cleanup EXIT

if curl -s -o /dev/null "http://localhost:$PORT/" 2>/dev/null; then
  OWNER_PID="$(lsof -ti:"$PORT" 2>/dev/null | head -n1)"
  OWNER_CMD="$([ -n "$OWNER_PID" ] && ps -p "$OWNER_PID" -o comm= 2>/dev/null)"
  if [ -n "$OWNER_PID" ] && [[ "$OWNER_CMD" == *bloxsmith-dev* ]]; then
    echo "dev-serve: reclaiming port $PORT from orphaned previous instance (pid $OWNER_PID)" >&2
    kill -TERM "$OWNER_PID" 2>/dev/null
    waited=0
    while kill -0 "$OWNER_PID" 2>/dev/null && [ "$waited" -lt 25 ]; do
      sleep 0.2
      waited=$((waited + 1))
    done
    kill -0 "$OWNER_PID" 2>/dev/null && kill -9 "$OWNER_PID" 2>/dev/null
  else
    echo "dev-serve: port $PORT already in use by another process — refusing to start" >&2
    exit 1
  fi
fi

echo "dev-serve: build UI + binary…"
LAST_UI=""
if rebuild_web; then
  LAST_UI="$(sig_ui)"
else
  echo "dev-serve: UI build failed (continuing with last good go/web)"
fi

DEVVER="dev-$(git rev-parse --short HEAD 2>/dev/null || echo local)"
LAST_GO=""
LAST_TRIED_GO="$LAST_GO"
GO_SUPPRESS_LOGGED=0
if ( cd go && go build -ldflags "-X main.version=$DEVVER" -o "$BIN" . ); then
  LAST_GO="$(sig_go)"
else
  echo "dev-serve: go build failed" >&2
  exit 1
fi

echo "dev-serve: serving :$PORT (DISABLE_UPDATE_CHECK, WEB_DIR)"
start

while sleep 2; do
  [ "$STOPPING" = "1" ] && break

  # self-heal: restart the binary if the port is dead and the process is gone
  if [ "$STOPPING" != "1" ] && ! curl -s -o /dev/null "http://localhost:$PORT/" 2>/dev/null && ! kill -0 "$SRV" 2>/dev/null; then
    echo "dev-serve: server down — restarting"
    start
  fi

  # UI edit -> vite rebuild into go/web (binary serves it from disk, no restart)
  NOW_UI="$(sig_ui)"
  if [ "$NOW_UI" != "$LAST_UI" ]; then
    echo "dev-serve: UI change -> rebuild"
    if rebuild_web; then
      LAST_UI="$NOW_UI"
      echo "dev-serve: ✓ UI rebuilt"
    else
      echo "dev-serve: UI build failed, will retry next cycle" >&2
    fi
  fi

  # Go edit -> rebuild binary, health-check, restart (or roll back)
  NOW_GO="$(sig_go)"
  if [ "$NOW_GO" != "$LAST_GO" ] && [ "$NOW_GO" != "$LAST_TRIED_GO" ]; then
    LAST_TRIED_GO="$NOW_GO"
    GO_SUPPRESS_LOGGED=0
    echo "dev-serve: Go change -> rebuild"
    DEVVER="dev-$(git rev-parse --short HEAD 2>/dev/null || echo local)"
    if ( cd go && go build -ldflags "-X main.version=$DEVVER" -o "$BIN.next" . ); then
      cp -f "$BIN" "$BIN.prev" 2>/dev/null
      mv -f "$BIN.next" "$BIN"
      restart_binary
      if health_check; then
        LAST_GO="$NOW_GO"
        LAST_TRIED_GO=""
        echo "dev-serve: ✓ Go rebuilt + restarted"
      else
        echo "dev-serve: health check failed, rolling back" >&2
        if [ -f "$BIN.prev" ]; then
          mv -f "$BIN.prev" "$BIN"
          restart_binary
        fi
      fi
    else
      rm -f "$BIN.next"
      echo "dev-serve: go build failed, keeping running binary" >&2
    fi
  elif [ "$NOW_GO" != "$LAST_GO" ] && [ -n "$LAST_TRIED_GO" ] && [ "$NOW_GO" = "$LAST_TRIED_GO" ] && [ "$GO_SUPPRESS_LOGGED" != "1" ]; then
    echo "dev-serve: Go sources match the last failed build — not retrying (edit to retry)"
    GO_SUPPRESS_LOGGED=1
  fi
done
